# Generated by Django 4.2.1 on 2023-06-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(db_column='category_name', max_length=50)),
                ('category_url_name', models.CharField(db_column='category_url_name', max_length=50)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='created_on')),
            ],
            options={
                'db_table': 'product_category',
            },
        ),
    ]
