# Generated by Django 4.2.1 on 2023-06-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='categories',
            field=models.ManyToManyField(db_column='categories', to='product.productcategorymodel'),
        ),
    ]
