# Generated by Django 4.2.1 on 2023-06-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productmodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='price',
            field=models.IntegerField(db_column='price', default=0),
            preserve_default=False,
        ),
    ]
