# Generated by Django 4.2.1 on 2023-06-05 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productmodel_slug_alter_productmodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='images',
            field=models.ImageField(db_column='images', height_field=500, null=True, upload_to='products/', verbose_name='Display Picture', width_field=500),
        ),
    ]
