# Generated by Django 4.2.1 on 2023-06-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productmodel_created_on_productmodel_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(db_column='slug', null=True),
        ),
    ]
