# Generated by Django 4.2.1 on 2023-06-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_productmodel_price_alter_productmodel_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(blank=True, db_column='slug', null=True),
        ),
    ]
