# Generated by Django 4.2.1 on 2023-06-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_productmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='images',
            field=models.ImageField(db_column='images', null=True, upload_to='products/', verbose_name='Display Picture'),
        ),
    ]
