# Generated by Django 4.2.1 on 2023-06-05 16:39

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_productmodel_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='images',
            field=models.ImageField(blank=True, db_column='images', null=True, upload_to=product.models.ProductModel.product_img_path, verbose_name='Display Picture'),
        ),
    ]
