# Generated by Django 4.2.1 on 2023-06-05 17:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_productmodel_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_description',
            field=ckeditor.fields.RichTextField(db_column='product_description', verbose_name='description'),
        ),
    ]
