# Generated by Django 4.2.1 on 2023-06-06 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0015_alter_productmodel_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_description',
            field=models.TextField(db_column='product_description', verbose_name='description'),
        ),
        migrations.CreateModel(
            name='InventoryModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='quantity')),
                ('rate', models.DecimalField(db_column='rate', decimal_places=3, max_digits=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, to='product.productmodel')),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
    ]
