# Generated by Django 4.2.1 on 2023-06-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_productcategorymodel_category_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategorymodel',
            name='category_url_name',
            field=models.CharField(blank=True, db_column='category_url_name', max_length=50, null=True),
        ),
    ]
