# Generated by Django 4.2.1 on 2023-06-09 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0019_alter_productcategorymodel_category_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='categories',
            field=models.ManyToManyField(db_column='categories', related_name='products', to='product.productcategorymodel'),
        ),
        migrations.CreateModel(
            name='OrderDetailModel',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(db_column='quantity')),
                ('total_price', models.DecimalField(db_column='total_price', decimal_places=3, max_digits=10)),
                ('customer_name', models.CharField(max_length=50)),
                ('primary_delivery_address', models.CharField(max_length=100)),
                ('secondary_delivery_address', models.CharField(blank=True, max_length=100, null=True)),
                ('ordered_date', models.DateField(auto_now_add=True)),
                ('order_staus', models.CharField(choices=[('CONFIRMED', 'CONFIRMED'), ('DISPTACHED', 'DISPTACHED'), ('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED')], default='CONFIRMED', max_length=20)),
                ('payment_completed', models.BooleanField(default=False)),
                ('ordered_by', models.ForeignKey(db_column='ordered_by', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, to='product.productmodel')),
            ],
            options={
                'db_table': 'order_details',
            },
        ),
    ]
