# Generated by Django 4.2.1 on 2023-06-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_productmodel_categories_orderdetailmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetailmodel',
            name='City',
            field=models.CharField(default=11, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetailmodel',
            name='postal_code',
            field=models.CharField(default=11, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetailmodel',
            name='customer_name',
            field=models.CharField(max_length=50, verbose_name='customer name'),
        ),
    ]
