# Generated by Django 4.2.1 on 2023-06-09 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_orderdetailmodel_city_orderdetailmodel_postal_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetailmodel',
            old_name='City',
            new_name='city',
        ),
    ]
