# Generated by Django 4.2.1 on 2023-06-03 08:47

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImagesModel',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('banner_title', models.ImageField(blank=True, db_column='banner_title', upload_to=home.models.BannerImagesModel.banner_directory_path)),
                ('banner_redirect_url', models.CharField(blank=True, db_column='banner_redirect_url', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'banner_images',
            },
        ),
    ]
