# Generated by Django 4.2.1 on 2023-06-04 16:50

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bannerimagesmodel_banner_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureProductModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=100)),
                ('description', models.CharField(db_column='description', max_length=200)),
                ('redirect_url', models.CharField(db_column='redirect_url', max_length=200)),
                ('feature_image', models.ImageField(db_column='feature_image', upload_to=home.models.FeatureProductModel.feature_directory_path)),
            ],
            options={
                'db_table': 'feature_products',
            },
        ),
    ]
