# Generated by Django 4.2.1 on 2023-06-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_featureproductmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureproductmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
