# Generated by Django 4.2.1 on 2023-06-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_featureproductmodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureproductmodel',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
