# Generated by Django 4.2.1 on 2023-06-12 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_orderdetailmodel_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_featureproductmodel_is_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCart',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cart_status', models.BooleanField(db_column='cart_status', default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, to='product.productmodel')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
